### ISSUE TITLE
Sobre o nome

### ISSUE THREAD

**Issue by Jadergomes** [bahiacoders/agenda-de-eventos#2]
Ja que estamos falando de BAHIA, por que não usamos os contextos linguísticos tão usados aqui. Tipo a agenda poderia se chamar (agendaÊ). Não é algo tão relevante, mas acho interessante apenas essa proposta, principalmente para iniciativas futuras do nosso próprio grupo.

**Comment by mvfsilva** [comment]
Achei interessante Jader;

**Comment by Jadergomes** [comment]
:)
